# Generated by Django 3.1.1 on 2020-09-29 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20200929_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
