# Generated by Django 3.1.1 on 2020-09-29 18:11

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200929_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='text',
            field=ckeditor.fields.RichTextField(),
        ),
    ]
