# Generated by Django 3.1.1 on 2020-09-29 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_auto_20200929_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.TextField(max_length=300),
        ),
    ]
