# Generated by Django 3.1.1 on 2020-10-07 18:40

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20201007_1754'),
    ]

    operations = [
        migrations.CreateModel(
            name='License',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Наименование')),
                ('img', models.ImageField(default='license_images/no-img.jpg', upload_to=main.models.get_image_filename, verbose_name='Изображение')),
            ],
        ),
        migrations.AlterModelOptions(
            name='new',
            options={'verbose_name': 'Новости', 'verbose_name_plural': 'Новости'},
        ),
        migrations.AlterField(
            model_name='block',
            name='type',
            field=models.CharField(max_length=50, verbose_name='Тип блока'),
        ),
    ]
