# Generated by Django 3.1.1 on 2020-10-11 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20201007_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='license',
            options={'verbose_name': 'Лицензия', 'verbose_name_plural': 'Лицензии'},
        ),
        migrations.AlterField(
            model_name='license',
            name='img',
            field=models.ImageField(default='license_images/no-img.jpg', upload_to='license_images/', verbose_name='Изображение'),
        ),
    ]
